Repository ba-st/Buoy, pull requests merged in 2023-08, with the labels that each got.

#81 Support for GemStone/S 64
  .github/workflows/unit-tests-gs64.yml
  README.md
  docs/README.md
  rowan/components/Deployment.ston
  rowan/components/README.md
  rowan/components/SUnit-Dependent-Extensions.ston
  rowan/components/Tests.ston
  rowan/project.ston
  rowan/projects/README.md
  rowan/specs/Buoy-CI.ston
  rowan/specs/README.md
  source/.properties
  source/Buoy-Collections-GS64-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/package.st
  source/Buoy-SUnit-GS64-Extensions/TestAsserter.extension.st
  source/Buoy-SUnit-GS64-Extensions/package.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits

#82 Conditions for GS64
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Conditions-Extensions/BlockClosure.extension.st
  source/Buoy-Conditions-Extensions/Boolean.extension.st
  source/Buoy-Conditions-Extensions/package.st
  source/Buoy-Conditions-Pharo-Extensions-Tests/RegexConditionTest.class.st
  source/Buoy-Conditions-Pharo-Extensions-Tests/package.st
  source/Buoy-Conditions-Pharo-Extensions/RegexCondition.class.st
  source/Buoy-Conditions-Pharo-Extensions/package.st
  source/Buoy-Metaprogramming-Extensions/Object.extension.st
  source/Buoy-Metaprogramming-Extensions/package.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits, OS: Linux

#84 Exception handling tests rewritten for GS64 compatibility
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Exception-Handling-Extensions-Tests/ExceptionHandlingSystemTest.class.st
  source/Buoy-Exception-Handling-Extensions-Tests/package.st
  source/Buoy-Exception-Handling-Extensions/BlockClosure.extension.st
  source/Buoy-Exception-Handling-Extensions/package.st
  source/Buoy-Exception-Handling-Tests/package.st
  source/Buoy-Exception-Handling/BlockClosure.extension.st
  source/Buoy-Exception-Handling/package.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits

#85 GS64: Add Metaprogramming, Dynamic-Binding and Comparison packages
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Collections-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections-Extensions/package.st
  source/Buoy-Collections-GS64-Extensions/AbstractDictionary.extension.st
  source/Buoy-Collections-GS64-Extensions/CharacterCollection.extension.st
  source/Buoy-Collections-GS64-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections/SequenceableCollection.extension.st
  source/Buoy-Comparison-Extensions/Object.extension.st
  source/Buoy-Comparison-Extensions/package.st
  source/Buoy-Dynamic-Binding/Optional.class.st
  source/Buoy-Exception-Handling-Extensions-Tests/package.st
  source/Buoy-Exception-Handling-Tests/ExceptionHandlingSystemTest.class.st
  source/Buoy-Exception-Handling-Tests/package.st
  source/Buoy-GS64-Compatibility/AbstractDictionary.class.st
  source/Buoy-GS64-Compatibility/ClassOrganizer.class.st
  source/Buoy-Math-GS64-Extensions/Number.extension.st
  source/Buoy-Math-GS64-Extensions/package.st
  source/Buoy-Metaprogramming-GS64-Extensions/Class.extension.st
  source/Buoy-Metaprogramming-Pharo-Extensions/Behavior.extension.st
  source/Buoy-Metaprogramming-Pharo-Extensions/Symbol.extension.st
  source/Buoy-Metaprogramming-Pharo-Extensions/package.st
  source/Buoy-Metaprogramming-Tests/NamespaceTest.class.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits

#86 GS64: Add Collections packages
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  rowan/components/scripts/defineExceptionAliases.st
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Collections-Extensions/Collection.extension.st
  source/Buoy-Collections-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections-GS64-Extensions/Array.extension.st
  source/Buoy-Collections-GS64-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections-Pharo-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections-Pharo-Extensions/package.st
  source/Buoy-Collections-Tests/OrderedSetTest.class.st
  source/Buoy-Collections/OrderedSet.class.st
  source/Buoy-Collections/SequenceableCollection.extension.st
  source/Buoy-GS64-Compatibility/OffsetError.class.st
  source/Buoy-Math-GS64-Extensions/Integer.extension.st
  source/Buoy-Math-GS64-Extensions/Number.extension.st
  source/Buoy-SUnit-GS64-Extensions/TestAsserter.extension.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits

#87 GS64: Add Math packages
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  rowan/components/scripts/defineExceptionAliases.st
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-GS64-Compatibility/BinaryFloat.class.st
  source/Buoy-GS64-Compatibility/ClassOrganizer.class.st
  source/Buoy-GS64-Compatibility/Collection.extension.st
  source/Buoy-Math-Extensions/Fraction.extension.st
  source/Buoy-Math-Extensions/Integer.extension.st
  source/Buoy-Math-Extensions/Number.extension.st
  source/Buoy-Math-Extensions/package.st
  source/Buoy-Math-GS64-Base-Extensions/BinaryFloat.extension.st
  source/Buoy-Math-GS64-Base-Extensions/Integer.extension.st
  source/Buoy-Math-GS64-Base-Extensions/Number.extension.st
  source/Buoy-Math-GS64-Base-Extensions/package.st
  source/Buoy-Math-GS64-Extensions/Number.extension.st
  source/Buoy-Math-GS64-Extensions/PartsPerFraction.extension.st
  source/Buoy-Math-GS64-Extensions/PerMille.extension.st
  source/Buoy-Math-GS64-Extensions/Percentage.extension.st
  source/Buoy-Math-Pharo-Extensions-Tests/PerMilleTest.extension.st
  source/Buoy-Math-Pharo-Extensions-Tests/PercentageTest.extension.st
  source/Buoy-Math-Pharo-Extensions-Tests/package.st
  source/Buoy-Math-Pharo-Extensions/PartsPerFraction.extension.st
  source/Buoy-Math-Pharo-Extensions/PerMille.extension.st
  source/Buoy-Math-Pharo-Extensions/Percentage.extension.st
  source/Buoy-Math-Pharo-Extensions/package.st
  source/Buoy-Math-Tests/BuoyNumberExtensionsTest.class.st
  source/Buoy-Math-Tests/PerMilleTest.class.st
  source/Buoy-Math-Tests/PercentageTest.class.st
  source/Buoy-Math/PartsPerFraction.class.st
  source/Buoy-Math/PerMille.class.st
  source/Buoy-Math/Percentage.class.st
  source/Buoy-SUnit-GS64-Extensions/TestCase.extension.st
  source/Buoy-SUnit-Pharo-Extensions/TestCase.extension.st
  source/Buoy-SUnit-Pharo-Extensions/package.st
Labels: Type: Feature, Platform: GemStone/S, Arch: 64bits

#88 GS64: Pre-release updates
  .github/workflows/loading-gs64-components.yml
  .github/workflows/notify.yml
  .github/workflows/unit-tests.yml
  README.md
  docs/README.md
  docs/reference/Baseline-groups.md
  docs/reference/Collections.md
  docs/reference/MOP.md
  docs/reference/Math.md
  docs/reference/SUnit.md
  rowan/components/Dependent-SUnit-Extensions.ston
  rowan/components/Tests.ston
  rowan/specs/Buoy-Dependent-SUnit-Extensions.ston
  rowan/specs/Buoy-Deployment.ston
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Collections-Tests/CollectionExtensionsTest.class.st
  source/Buoy-Collections-Tests/StringExtensionsTest.class.st
Labels: Type: Improvement, Platform: GemStone/S, Arch: 64bits

#91 Add missing package in Deployment group
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
Labels: Type: Defect, Platform: Pharo

#92 GS/64 extensions to base clases needed for Zinc
  .github/workflows/loading-groups.yml
  .github/workflows/unit-tests.yml
  README.md
  rowan/components/Deployment.ston
  rowan/components/scripts/defineExceptionAliases.st
  rowan/components/scripts/definePostLoadExceptionAliases.st
  source/Buoy-Collections-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/AbstractDictionary.extension.st
  source/Buoy-Collections-GS64-Extensions/Array.extension.st
  source/Buoy-Collections-GS64-Extensions/Character.extension.st
  source/Buoy-Collections-GS64-Extensions/CharacterCollection.extension.st
  source/Buoy-Collections-GS64-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/Object.extension.st
  source/Buoy-Collections-GS64-Extensions/OrderedDictionary.class.st
  source/Buoy-Collections-GS64-Extensions/PositionableStream.extension.st
  source/Buoy-Collections-Tests/DictionaryExtensionsTest.class.st
  source/Buoy-Collections-Tests/OrderedDictionaryExtensionsTest.class.st
  source/Buoy-Collections-Tests/StreamExtensionsTest.class.st
  source/Buoy-Collections-Tests/StringExtensionsTest.class.st
  source/Buoy-GS64-Compatibility/GsSocket.class.st
  source/Buoy-Math-GS64-Base-Extensions/DomainError.class.st
  source/Buoy-Metaprogramming-GS64-Extensions/DynamicVariable.class.st
  source/Buoy-Metaprogramming-GS64-Extensions/Object.extension.st
  source/Buoy-Metaprogramming-Tests/DynamicVariableForTesting.class.st
  source/Buoy-Metaprogramming-Tests/DynamicVariableTest.class.st
Labels: Type: Improvement, Platform: GemStone/S

#93 Add more extensions for GS64
  rowan/components/Deployment.ston
  rowan/components/scripts/defineClassAliases.st
  source/Buoy-Collections-GS64-Extensions/Collection.extension.st
  source/Buoy-Collections-GS64-Extensions/OffsetError.extension.st
  source/Buoy-Collections-GS64-Extensions/SequenceableCollection.extension.st
  source/Buoy-Collections-Tests/CollectionExtensionsTest.class.st
  source/Buoy-GS64-Compatibility/ArgumentError.class.st
  source/Buoy-GS64-Compatibility/GsCurrentSession.class.st
  source/Buoy-GS64-Compatibility/GsSocket.class.st
  source/Buoy-GS64-Compatibility/OffsetError.class.st
  source/Buoy-Math-GS64-Base-Extensions/Integer.extension.st
  source/Buoy-Metaprogramming-Extensions/LanguagePlatform.class.st
  source/Buoy-Metaprogramming-GS64-Extensions/Class.extension.st
  source/Buoy-Metaprogramming-GS64-Extensions/GemStone64Platform.class.st
  source/Buoy-Metaprogramming-Pharo-Extensions/PharoPlatform.class.st
  source/Buoy-Metaprogramming-Tests/LanguagePlatformTest.class.st
  source/Buoy-SUnit-GS64-Extensions/TestAsserter.extension.st
  source/Buoy-SUnit-Pharo-Extensions/TestAsserter.extension.st
Labels: Type: Improvement, Platform: GemStone/S, Arch: 64bits

#94 Add extensions needed for NeoJSON
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
  source/Buoy-Chronology-GS64-Extensions/Date.extension.st
  source/Buoy-Chronology-GS64-Extensions/package.st
  source/Buoy-Chronology-Pharo-Extensions/Date.extension.st
  source/Buoy-Chronology-Pharo-Extensions/package.st
  source/Buoy-Chronology-Tests/DateExtensionsTest.class.st
  source/Buoy-Chronology-Tests/package.st
  source/Buoy-Math-GS64-Base-Extensions/BinaryFloat.extension.st
  source/Buoy-Math-GS64-Base-Extensions/Integer.extension.st
  source/Buoy-Math-GS64-Base-Extensions/Number.extension.st
  source/Buoy-Math-Pharo-Extensions/Integer.extension.st
  source/Buoy-Math-Tests/BuoyNumberExtensionsTest.class.st
Labels: Type: Improvement, Platform: Pharo, Platform: GemStone/S, Arch: 64bits

#98 Add default group to Baseline to avoid loading GS64 code by mistake
  source/BaselineOfBuoy/BaselineOfBuoy.class.st
Labels: Type: Improvement

#99 Improve GS64 component definitions
  docs/how-to/how-to-load-in-pharo.md
  docs/reference/BindingsAndOptionals.md
  docs/reference/Collections.md
  docs/reference/Comparison.md
  docs/reference/Conditions.md
  docs/reference/Namespaces.md
  docs/tutorial/Assertions.md
  rowan/components/Dependent-SUnit-Extensions.ston
  rowan/components/Deployment.ston
  rowan/components/Tests.ston
  rowan/specs/Buoy-CI.ston
  rowan/specs/Buoy-Dependent-SUnit-Extensions.ston
  rowan/specs/Buoy-Deployment.ston
  source/Buoy-Metaprogramming-Extensions/LanguagePlatform.class.st
Labels: Type: Improvement, Platform: GemStone/S, Arch: 64bits
